# Generated by Django on 2021-04-16 (to'g'irlangan versiya SQLite uchun)

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='array',
            field=models.TextField(default='[]', blank=True, null=True),
        ),
    ]
