# Generated by Django 5.2 on 2025-04-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', models.TextField(blank=True, default='[]', null=True)),
            ],
        ),
    ]
